### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by thbeu** [gepcel/GisViewer#4]
Thanks for this TC plugin.

I followed the documentation and installed first the tcdotnetinterface 1.4 and then the GisViewer plugin in TC 11.02 on Win10. But still I get a FileNotFoundException an the DotSpatial assemblies when trying to view a shapefile:

> FileNotFoundException: Die Datei oder Assembly "DotSpatial.Controls, Version=1.9.0.0, Culture=neutral, PublicKeyToken=4d9e49339a7d240c" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
   bei GisViewer.GisViewerControl.InitializeComponent()
   bei GisViewer.GisViewerControl..ctor()
   bei GisViewer.GisViewer.Load(String fileToLoad, ShowFlags showFlags)
   bei OY.TotalCommander.TcPluginInterface.Lister.ListerPlugin.Load(String fileToLoad, ShowFlags showFlags)
   bei OY.TotalCommander.WlxWrapper.ListerWrapper.LoadW(IntPtr parentWin, String fileToLoad, Int32 flags)

I tried to add all DotSpatial assemblies to the GAC using gacutil, but still no success.

Do you have any idea how to the GisViewer plugin working?

**Comment by gepcel** [comment]
I'm still using this on several systems. I don't what's wrong here, but I'm sure we can make this work.

I think the key point here is :
(1) to put all files in the proper directory and set it up properly as a wlx totalcmd plugin.
(2) Install the `tcdotnetinterface 1.4`.

For example: 
Add `%COMMANDER_PATH%\plugins\wlx\GisViewer\GisViewer.wlx` to totalcmd wlx plugin.
In the `%COMMANDER_PATH%\plugins\wlx\GisViewer\` directory files are as:

```
%COMMANDER_PATH%\plugins\wlx\GisViewer：
│  GisViewer.dll
│  GisViewer.dll.config
│  GisViewer.pdb
│  GisViewer.wlx
│  GisViewer.wlx.config
│  GisViewer.wlx64
│  GisViewer.wlx64.config
│  readme.txt
└─DotSpatial
    │  DotSpatial.Controls.dll
    │  DotSpatial.Controls.pdb
    │  DotSpatial.Data.dll
    │  DotSpatial.Data.Forms.dll
    │  DotSpatial.Data.Forms.pdb
    │  DotSpatial.Data.pdb
    │  DotSpatial.Extensions.dll
    │  DotSpatial.Extensions.pdb
    │  DotSpatial.Modeling.Forms.dll
    │  DotSpatial.Modeling.Forms.pdb
    │  DotSpatial.Mono.dll
    │  DotSpatial.Mono.pdb
    │  DotSpatial.Projections.dll
    │  DotSpatial.Projections.Forms.dll
    │  DotSpatial.Projections.Forms.pdb
    │  DotSpatial.Projections.pdb
    │  DotSpatial.Serialization.dll
    │  DotSpatial.Serialization.pdb
    │  DotSpatial.Symbology.dll
    │  DotSpatial.Symbology.Forms.dll
    │  DotSpatial.Symbology.Forms.pdb
    │  DotSpatial.Symbology.pdb
    │  DotSpatial.Topology.dll
    │  DotSpatial.Topology.pdb
    │  
    ├─cs
    │      DotSpatial.Projections.Forms.resources.dll
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    ├─de
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─de-DE
    │      DotSpatial.Controls.resources.dll
    │      DotSpatial.Projections.Forms.resources.dll
    │      DotSpatial.Symbology.Forms.resources.dll
    │      DotSpatial.Symbology.resources.dll
    │      
    ├─el
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─en-US
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    ├─it
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    ├─it-IT
    │      DotSpatial.Controls.resources.dll
    │      DotSpatial.Projections.Forms.resources.dll
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    ├─ja-JP
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─lt
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─nl
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─pt
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─pt-BR
    │      DotSpatial.Controls.resources.dll
    │      DotSpatial.Projections.Forms.resources.dll
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    ├─ro
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─th
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─vi-VN
    │      DotSpatial.Projections.Forms.resources.dll
    │      
    ├─zh-CN
    │      DotSpatial.Controls.resources.dll
    │      DotSpatial.Data.Forms.resources.dll
    │      DotSpatial.Modeling.Forms.resources.dll
    │      DotSpatial.Projections.Forms.resources.dll
    │      DotSpatial.Symbology.Forms.resources.dll
    │      
    └─zh-MO
            DotSpatial.Modeling.Forms.resources.dll
```

Would you mind try this and let me know what you got?

**Comment by thbeu** [comment]
Thanks for the reply.

There is no GisViewer.dll.config file on my machine. Could that be an error cause? Apart from that it is setup as expected.

**Comment by thbeu** [comment]
Edit: Yes, that solved the problem. Thanks!

**Comment by gepcel** [comment]
> Edit: Yes, that solved the problem. Thanks!

Happy to know. This plugin works for years for me and well meet my needs. I hope you'll like it.

**Comment by thbeu** [comment]
Yes, looks good so far!

About installation: It's just that GisViewer.dll.config file is missing in the download package from https://totalcmd.net/download.php?id=GisViewer

**Comment by gepcel** [comment]
I've updated it. [https://totalcmd.net/plugring/GisViewer.html]()
